name: API Test and deploy
on:
  push:
    paths:
      - 'services/tasks_api/**'
      - '.github/workflows/api.yml'

jobs:
  code-quality:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.13]
        uv-version: [0.8.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: services/tasks_api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ matrix.uv-version }}
      - name: Install dependencies
        run: uv pip install -r pyproject.toml
      - name: Run black
        run: uv run black . --check
      - name: Run isort
        run: uv run isort . --check-only
      - name: Run flake8
        run: uv run flake8 .
      - name: Run bandit
        run: uv run bandit .